name: Scala CI

on:
  push:
  pull_request:

jobs:
  check-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ViperServer repo
        uses: actions/checkout@v2
      - name: Check license headers
        uses: viperproject/check-license-header@v1
        with:
          path: ./
          config: ./.github/license-check/config.json
          strict: true

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ViperServer
      uses: actions/checkout@v2
      with:
        path: viperServer
    - name: Checkout Silver
      uses: actions/checkout@v2
      with:
        repository: viperproject/silver
        path: silver
    - name: Checkout Silicon
      uses: actions/checkout@v2
      with:
        repository: viperproject/silicon
        path: silicon
    - name: Checkout Carbon
      uses: actions/checkout@v2
      with:
        repository: viperproject/carbon
        path: carbon
    
    - name: Symbolically link Silver to Carbon
      run: cd carbon; ln --symbolic ../silver
    - name: Symbolically link Silver to Silicon
      run: cd silicon; ln --symbolic ../silver
    - name: Symbolically link Silver to ViperServer
      run: cd viperServer; ln --symbolic ../silver
    - name: Symbolically link Carbon to ViperServer
      run: cd viperServer; ln --symbolic ../carbon
    - name: Symbolically link Silicon to ViperServer
      run: cd viperServer; ln --symbolic ../silicon
    
    - name: Install Z3-4.8.6
      uses: pavpanchekha/setup-z3
      with:
        version: 4.8.6
        architecture: x64
    
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: '15.0.1'
        architecture: x64

    - name: Install SBT
      run: echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list; curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add; sudo apt-get update; sudo apt-get install sbt

    - name: Assemble project
      run: cd viperServer; sbt assembly
        
    - name: test project
      run: cd viperServer; export Z3_EXE="/usr/bin/z3"; env > print_dir.txt; sbt test
      
